language: ruby
rvm:
- 2.3.3
sudo: false
dist: trusty
addons:
  postgresql: '9.6'
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate RAILS_ENV=test
#before_install:
#  - bundle exec rails s -d
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost
script:
  - bundle exec rspec
  - bundle exec cucumber -p headless
