language: ruby
rvm:
- 2.3.3
sudo: false
dist: trusty
addons:
  chrome: stable
  postgresql: '9.6'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate RAILS_ENV=test

