require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe BlogsController, type: :controller do

  let(:valid_attributes) {
    { title: 'lorem ipsum', body: 'lorem ipsum.. lorem ipsum.. lorem ipsum.. '}
  }

  let(:invalid_attributes) { { title: '', body: '' } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BlogsController. Be sure to keep this updated too.
  let(:owner) { FactoryGirl.create(:owner) }
  let(:valid_session) { { user_id: owner.id} }

  describe "GET #index" do
    it "returns a success response" do
      blog = Blog.create! valid_attributes
      get :index, params: {}
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      blog = Blog.create! valid_attributes
      get :show, params: {id: blog.to_param}
      expect(response).to be_success
    end

    context "record does not exist" do
      it "redirects to index" do
        get :show, params: {id: 0}
        expect(response).to redirect_to(blogs_path)
      end
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      blog = Blog.create! valid_attributes
      get :edit, params: {id: blog.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Blog" do
        expect {
          post :create, params: {blog: valid_attributes}, session: valid_session
        }.to change(Blog, :count).by(1)
      end

      it "redirects to the created blog & shows success message" do
        post :create, params: {blog: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Blog.last)
        expect(flash[:success]).to eq "Blog was successfully created"
      end
    end

    context "with invalid params & shows error messages" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {blog: invalid_attributes}, session: valid_session
        expect(response).to be_success
        expect(flash[:danger]).to contain_exactly("Title can't be blank", "Body can't be blank")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do
        { title: 'update another title' }
      end

      it "updates the requested blog" do
        blog = Blog.create! valid_attributes
        put :update, params: {id: blog.to_param, blog: new_attributes}, session: valid_session
        blog.reload
        expect(blog.title).to eq new_attributes[:title]
      end

      it "redirects to the blog & show success message " do
        blog = Blog.create! valid_attributes
        put :update, params: {id: blog.to_param, blog: valid_attributes}, session: valid_session
        expect(response).to redirect_to(blog)
        expect(flash[:success]).to eq "Blog was successfully updated."
      end
    end

    context "with invalid params & show error messages" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        blog = Blog.create! valid_attributes
        put :update, params: {id: blog.to_param, blog: invalid_attributes}, session: valid_session
        expect(response).to be_success
        expect(flash[:danger]).to include("Title can't be blank", "Body can't be blank")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested blog" do
      blog = Blog.create! valid_attributes
      expect {
        delete :destroy, params: {id: blog.to_param}, session: valid_session
      }.to change(Blog, :count).by(-1)
    end

    it "redirects to the blogs list & shows success message" do
      blog = Blog.create! valid_attributes
      delete :destroy, params: {id: blog.to_param}, session: valid_session
      expect(response).to redirect_to(blogs_url)
      expect(flash[:success]).to eq "Blog was successfully destroyed."
    end
  end
end
